# Copyright 2024 Bloomberg Finance L.P.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""CLI entry point for the BlazingMQ XSD-to-C++ code generator.

Usage::

    python -m blazingmq.codegen \\
        --package mqbcfg \\
        --msgComponent messages \\
        --output-dir src/groups/mqb/mqbcfg \\
        src/groups/mqb/mqbcfg/mqbcfg.xsd

This is a drop-in open-source replacement for Bloomberg's internal
``bas_codegen.pl`` tool.  It reads a BlazingMQ ``.xsd`` schema and
emits a BDE-style ``_messages.h`` / ``_messages.cpp`` pair that is
wire-compatible with the Perl tool's output.

The generated files include a copyright header (configurable via
``--copyright-file``) and a codegen provenance stamp.  Pass
``--clang-format`` to run ``clang-format -i`` on the output
automatically.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

from .parser import parse
from .emitter_h import emit_header
from .emitter_cpp import emit_source


DEFAULT_COPYRIGHT = """\
// Copyright {year} Bloomberg Finance L.P.
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
"""


def _build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="python -m blazingmq.codegen",
        description="Generate BDE-style C++ from a BlazingMQ XSD schema.",
    )
    p.add_argument(
        "xsd",
        help="Path to the .xsd schema file.",
    )
    p.add_argument(
        "--package",
        required=True,
        help="BDE package name (e.g. mqbcfg, bmqp_ctrlmsg).",
    )
    p.add_argument(
        "--msgComponent",
        required=True,
        dest="component",
        help="Component name (e.g. messages, values).",
    )
    p.add_argument(
        "--output-dir",
        "-o",
        default=".",
        help="Directory to write generated files (default: current directory).",
    )
    p.add_argument(
        "--copyright-file",
        default=None,
        help="Path to a file containing the copyright header text. "
        "If omitted, uses the default Apache 2.0 header.",
    )
    p.add_argument(
        "--copyright-years",
        default=None,
        help="Copyright years string (e.g. '2024', '2014-2026'). "
        "Used with the default copyright template when --copyright-file "
        "is not provided.",
    )
    p.add_argument(
        "--codegen-version",
        default=None,
        help="Version stamp for the GENERATED BY comment "
        "(default: derived from current date as YYYY.MM.DD).",
    )
    p.add_argument(
        "--clang-format",
        action="store_true",
        help="Run clang-format -i on the generated files.",
    )
    # Accept (and ignore) Perl-tool flags for backward compatibility
    # with existing scripts that pass these through.
    p.add_argument("-m", dest="_mode", default="msg", help=argparse.SUPPRESS)
    p.add_argument(
        "--noAggregateConversion",
        action="store_true",
        dest="_no_agg",
        help=argparse.SUPPRESS,
    )
    p.add_argument(
        "--noExternalization",
        action="store_true",
        dest="_no_ext",
        help=argparse.SUPPRESS,
    )
    p.add_argument(
        "--noIdent", action="store_true", dest="_no_ident", help=argparse.SUPPRESS
    )
    return p


def main(argv: list[str] | None = None) -> int:
    args = _build_parser().parse_args(argv)

    xsd_path = Path(args.xsd)
    if not xsd_path.exists():
        print(f"error: XSD file not found: {xsd_path}", file=sys.stderr)
        return 1

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    # Build copyright header
    if args.copyright_file:
        copyright_path = Path(args.copyright_file)
        if not copyright_path.exists():
            print(f"error: copyright file not found: {copyright_path}", file=sys.stderr)
            return 1
        copyright_text = copyright_path.read_text(encoding="utf-8")
    else:
        from datetime import date  # pylint: disable=import-outside-toplevel

        year = args.copyright_years or str(date.today().year)
        copyright_text = DEFAULT_COPYRIGHT.format(year=year)

    # Derive codegen version
    if args.codegen_version:
        codegen_ver = args.codegen_version
    else:
        from datetime import date  # pylint: disable=import-outside-toplevel

        codegen_ver = date.today().strftime("%Y.%m.%d")

    # Parse schema
    try:
        schema = parse(xsd_path)
    except (ValueError, KeyError, ET.ParseError) as e:
        print(f"error: failed to parse {xsd_path}: {e}", file=sys.stderr)
        return 1

    # Generate
    xsd_name = xsd_path.name
    try:
        h_content = emit_header(
            schema,
            pkg=args.package,
            component=args.component,
            copyright=copyright_text,
            xsd_name=xsd_name,
            codegen_version=codegen_ver,
        )
        cpp_content = emit_source(
            schema,
            pkg=args.package,
            component=args.component,
            copyright=copyright_text,
            xsd_name=xsd_name,
            codegen_version=codegen_ver,
        )
    except (ValueError, KeyError, AttributeError) as e:
        print(f"error: code generation failed: {e}", file=sys.stderr)
        return 1

    # Write output files
    component_full = f"{args.package}_{args.component}"
    h_path = output_dir / f"{component_full}.h"
    cpp_path = output_dir / f"{component_full}.cpp"

    h_path.write_text(h_content, encoding="utf-8")
    cpp_path.write_text(cpp_content, encoding="utf-8")

    print(f"Generated {h_path}")
    print(f"Generated {cpp_path}")

    # Optionally run clang-format
    if args.clang_format:
        for path in (h_path, cpp_path):
            try:
                subprocess.run(
                    ["clang-format", "-i", str(path)],
                    check=True,
                )
            except FileNotFoundError:
                print(
                    "warning: clang-format not found, skipping formatting",
                    file=sys.stderr,
                )
                break
            except subprocess.CalledProcessError as e:
                print(f"warning: clang-format failed on {path}: {e}", file=sys.stderr)

    return 0


if __name__ == "__main__":
    sys.exit(main())
